apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- install-prometheus.yaml
- prometheus-view.yaml
- configure-prometheus.yaml
- ./servicemonitors/
- alertmanager-config.yaml

namespace: "appstudio-workload-monitoring"

generatorOptions:
  disableNameSuffixHash: true
