apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: monitoring-prometheus-oauth-config-path.yaml
    target:
      name: monitoring-prometheus-oauth-config
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
  - path: monitoring-prometheus-sm-secret-path.yaml
    target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      labelSelector: prometheus=appstudio-workload
