apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    prometheus: appstudio-workload
  name: integration-service
  namespace: integration-service
spec:
  endpoints:
  - path: /metrics
    port: https
    scheme: https
    bearerTokenSecret:
      name: ""
      key: token
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - integration-service
  selector:
    matchLabels:
      control-plane: controller-manager
